### ISSUE TITLE
Release mode require for ExprTk

### ISSUE THREAD

**Issue by ArashPartow** [hshively/shi.work.Equation_Interpreter#1]
Hello, I'm the author of ExprTk, can you please let me know what is the problem you're seeing when using ExprTk, that requires a release mode _only_ compilation?

Quote:
> Must be compiled under release mode so that the equation processing library is happy

I've tested ExprTk extensively on the MSVC platform versions **7.1** to **14.1** in both debug and release build for both win32 and x64 targets.

**Comment by haydenshively** [comment]
I'm a relatively novice programmer working on this for my high school robotics team, so I'm sure I'm doing something wrong. All I know is that I was using Visual Studios 2017, and when I tried to run it in debug mode it wouldn't work. I apologize if my terminology is off.

**Comment by ArashPartow** [comment]
> I'm a relatively novice programmer 

We've all had to start at the start.  :D

WRT your issue, typically with Visual Studio, in order to compile ExprTk one needs to add the **/bigobj** option in the **C/C++->Command Line** settings of the Project Properties, in both Debug and Release modes. Like so:

![msvc_exprtk](https://cloud.githubusercontent.com/assets/513642/23980456/a40acb58-0a53-11e7-8698-0bfb5f1c6f33.png)



My thinking is that you've probably got it setup in Release but not in Debug mode.

**Comment by haydenshively** [comment]
That fixed it. Thanks so much!
